'use client';

import { Download, FileText } from 'lucide-react';

interface BugFix {
  file: string;
  severity: string;
  description: string;
  before: string;
  after: string;
  timeSaved: number;
  timestamp: Date;
}

interface ExportReportProps {
  fixes: BugFix[];
  projectName?: string;
}

export default function ExportReport({ fixes, projectName = 'Project' }: ExportReportProps) {
  const generateMarkdown = () => {
    const totalTimeSaved = fixes.reduce((sum, fix) => sum + fix.timeSaved, 0);
    const severityCounts = fixes.reduce((acc, fix) => {
      acc[fix.severity] = (acc[fix.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    let markdown = `# Bug Fix Report - ${projectName}\n\n`;
    markdown += `**Generated:** ${new Date().toLocaleString()}\n\n`;
    markdown += `## Summary\n\n`;
    markdown += `- **Total Bugs Fixed:** ${fixes.length}\n`;
    markdown += `- **Time Saved:** ${Math.floor(totalTimeSaved / 60)}h ${totalTimeSaved % 60}m\n`;
    markdown += `- **Quality Improvement:** ${Math.round((fixes.length / (fixes.length + 10)) * 100)}%\n\n`;
    
    markdown += `### By Severity\n\n`;
    Object.entries(severityCounts).forEach(([severity, count]) => {
      markdown += `- **${severity.charAt(0).toUpperCase() + severity.slice(1)}:** ${count}\n`;
    });
    
    markdown += `\n## Detailed Fixes\n\n`;
    
    fixes.forEach((fix, index) => {
      markdown += `### ${index + 1}. ${fix.file}\n\n`;
      markdown += `**Severity:** ${fix.severity}  \n`;
      markdown += `**Time Saved:** ${fix.timeSaved} minutes  \n`;
      markdown += `**Fixed:** ${fix.timestamp.toLocaleString()}  \n\n`;
      markdown += `**Issue:** ${fix.description}\n\n`;
      markdown += `**Before:**\n\`\`\`\n${fix.before}\n\`\`\`\n\n`;
      markdown += `**After:**\n\`\`\`\n${fix.after}\n\`\`\`\n\n`;
      markdown += `---\n\n`;
    });
    
    markdown += `## Recommendations\n\n`;
    markdown += `- Run comprehensive tests to verify all fixes\n`;
    markdown += `- Review edge cases mentioned in AI confidence scores\n`;
    markdown += `- Consider adding automated tests for fixed bugs\n`;
    markdown += `- Update documentation if API changes were made\n\n`;
    markdown += `---\n\n`;
    markdown += `*Generated by BugReaper - AI-Powered Bug Fixing*\n`;
    
    return markdown;
  };

  const generateHTML = () => {
    const totalTimeSaved = fixes.reduce((sum, fix) => sum + fix.timeSaved, 0);
    const severityCounts = fixes.reduce((acc, fix) => {
      acc[fix.severity] = (acc[fix.severity] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bug Fix Report - ${projectName}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #f5f5f5;
      color: #333;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 40px;
      border-radius: 12px;
      margin-bottom: 30px;
    }
    .header h1 { margin: 0 0 10px 0; }
    .header p { margin: 0; opacity: 0.9; }
    .summary {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }
    .stat-card {
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .stat-card h3 {
      margin: 0 0 10px 0;
      font-size: 14px;
      color: #666;
      text-transform: uppercase;
    }
    .stat-card .value {
      font-size: 32px;
      font-weight: bold;
      color: #667eea;
    }
    .fix-item {
      background: white;
      padding: 30px;
      border-radius: 8px;
      margin-bottom: 20px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }
    .fix-header {
      display: flex;
      justify-content: space-between;
      align-items: start;
      margin-bottom: 20px;
    }
    .severity {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: bold;
      text-transform: uppercase;
    }
    .severity.critical { background: #fee; color: #c00; }
    .severity.high { background: #ffeaa7; color: #d63031; }
    .severity.medium { background: #fff3cd; color: #856404; }
    .severity.low { background: #d1ecf1; color: #0c5460; }
    pre {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 6px;
      overflow-x: auto;
      border-left: 4px solid #667eea;
    }
    code {
      font-family: 'Monaco', 'Menlo', monospace;
      font-size: 13px;
    }
    .diff-before { border-left-color: #dc3545; }
    .diff-after { border-left-color: #28a745; }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎃 Bug Fix Report</h1>
    <p>${projectName} • Generated ${new Date().toLocaleString()}</p>
  </div>
  
  <div class="summary">
    <div class="stat-card">
      <h3>Bugs Fixed</h3>
      <div class="value">${fixes.length}</div>
    </div>
    <div class="stat-card">
      <h3>Time Saved</h3>
      <div class="value">${Math.floor(totalTimeSaved / 60)}h ${totalTimeSaved % 60}m</div>
    </div>
    <div class="stat-card">
      <h3>Quality Score</h3>
      <div class="value">${Math.round((fixes.length / (fixes.length + 10)) * 100)}%</div>
    </div>
  </div>

  <h2>Fixes by Severity</h2>
  ${Object.entries(severityCounts).map(([severity, count]) => 
    `<span class="severity ${severity}">${severity}: ${count}</span>`
  ).join(' ')}

  <h2 style="margin-top: 40px;">Detailed Fixes</h2>
  ${fixes.map((fix, index) => `
    <div class="fix-item">
      <div class="fix-header">
        <div>
          <h3>${index + 1}. ${fix.file}</h3>
          <p style="color: #666; margin: 5px 0;">${fix.description}</p>
        </div>
        <span class="severity ${fix.severity}">${fix.severity}</span>
      </div>
      
      <p><strong>Time Saved:</strong> ${fix.timeSaved} minutes</p>
      <p><strong>Fixed:</strong> ${fix.timestamp.toLocaleString()}</p>
      
      <h4>Before:</h4>
      <pre class="diff-before"><code>${fix.before.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></pre>
      
      <h4>After:</h4>
      <pre class="diff-after"><code>${fix.after.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></pre>
    </div>
  `).join('')}

  <div style="margin-top: 40px; padding: 20px; background: #e3f2fd; border-radius: 8px;">
    <h3>📋 Recommendations</h3>
    <ul>
      <li>Run comprehensive tests to verify all fixes</li>
      <li>Review edge cases mentioned in AI confidence scores</li>
      <li>Consider adding automated tests for fixed bugs</li>
      <li>Update documentation if API changes were made</li>
    </ul>
  </div>

  <footer style="margin-top: 40px; text-align: center; color: #999;">
    <p>Generated by BugReaper - AI-Powered Bug Fixing</p>
  </footer>
</body>
</html>
    `.trim();
  };

  const downloadMarkdown = () => {
    const markdown = generateMarkdown();
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bug-fix-report-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadHTML = () => {
    const html = generateHTML();
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bug-fix-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (fixes.length === 0) return null;

  return (
    <div className="flex gap-2">
      <button
        onClick={downloadMarkdown}
        className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 text-sm"
      >
        <Download className="w-4 h-4" />
        Export MD
      </button>
      <button
        onClick={downloadHTML}
        className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors flex items-center gap-2 text-sm"
      >
        <FileText className="w-4 h-4" />
        Export HTML
      </button>
    </div>
  );
}
